import './style.css';import {BeansDB} from './storage/db';import {Renderer} from './render/renderer';import {Board,Camera,CHUNK_SIZE,chunksForBounds,chunkId,Layer,Point,SceneObject,Stroke,Tool,uid,boundsOfPoints} from './core/types';import {QuadTree} from './core/quadtree';
class App{db=new BeansDB();canvas=document.createElement('canvas');r=new Renderer(this.canvas);cam:Camera={x:-innerWidth/2,y:-innerHeight/2,zoom:1,targetZoom:1};tool:Tool='pen';prev:Tool='pen';board!:Board;layers:Layer[]=[];chunks=new Map<string,any>();qt=new QuadTree({x:-1e7,y:-1e7,w:2e7,h:2e7});objects:SceneObject[]=[];drawing=false;pan=false;last={x:0,y:0};stroke:Point[]=[];undo:SceneObject[][]=[];redo:SceneObject[][]=[];stab=45;worker=new Worker(new URL('./workers/simplify.worker.ts',import.meta.url),{type:'module'});ui=document.createElement('div');
async start(){document.querySelector('#app')!.append(this.canvas,this.ui);this.board=await this.db.ensureDefaultBoard();await this.loadBoard(this.board.id);this.bind();this.buildUI();this.loop();setInterval(()=>this.saveDirty(),2500)}
async loadBoard(id:string){this.chunks.clear();this.qt.clear();this.objects=[];this.board=(await this.db.get('boards',id))!;this.layers=(await this.db.all<Layer&{boardId:string}>('layers')).filter(l=>l.boardId===id);await this.stream();this.r.markAll()}
visibleLayers(){return new Set(this.layers.filter(l=>l.visible).map(l=>l.id))}async stream(){const cells=chunksForBounds(this.r.worldView(this.cam,CHUNK_SIZE));const needed=new Set(cells.map(c=>chunkId(this.board.id,c.cx,c.cy)));for(const id of [...this.chunks.keys()])if(!needed.has(id)){this.chunks.delete(id)}const missing=cells.filter(c=>!this.chunks.has(chunkId(this.board.id,c.cx,c.cy)));(await this.db.chunks(this.board.id,missing)).forEach(ch=>{this.chunks.set(ch.id,ch);ch.objects.forEach(o=>this.qt.insert(o))});this.objects=[...this.chunks.values()].flatMap(c=>c.objects)}
loop=async()=>{this.cam.zoom+=(this.cam.targetZoom-this.cam.zoom)*.18;await this.stream();this.r.render(this.cam,this.objects,this.visibleLayers());requestAnimationFrame(this.loop)}
screen(e:PointerEvent|WheelEvent){return{x:this.cam.x+e.clientX/this.cam.zoom,y:this.cam.y+e.clientY/this.cam.zoom,p:(e as PointerEvent).pressure||.5,t:performance.now()}}
bind(){this.canvas.oncontextmenu=e=>e.preventDefault();this.canvas.onpointerdown=e=>{this.canvas.setPointerCapture(e.pointerId);this.last={x:e.clientX,y:e.clientY};if(e.button===1||e.button===2||this.tool==='hand'){this.pan=true;return}if(this.tool==='pen'||this.tool==='highlighter'||this.tool==='eraser'){this.drawing=true;this.stroke=[this.screen(e)]}};this.canvas.onpointermove=e=>{if(this.pan){this.cam.x-=(e.clientX-this.last.x)/this.cam.zoom;this.cam.y-=(e.clientY-this.last.y)/this.cam.zoom;this.last={x:e.clientX,y:e.clientY};return}if(this.drawing)this.stroke.push(this.screen(e))};this.canvas.onpointerup=e=>{this.pan=false;if(!this.drawing)return;this.drawing=false;if(this.tool==='eraser')this.erase(this.stroke);else this.finishStroke(this.tool==='highlighter')};addEventListener('wheel',(e:WheelEvent)=>{e.preventDefault();if(e.ctrlKey){const before=this.screen(e);this.cam.targetZoom=Math.min(8,Math.max(.08,this.cam.targetZoom*(e.deltaY<0?1.15:.87)));const after=this.screen(e);this.cam.x+=before.x-after.x;this.cam.y+=before.y-after.y}else if(e.shiftKey)this.cam.x+=e.deltaY/this.cam.zoom;else this.cam.y+=e.deltaY/this.cam.zoom},{passive:false});addEventListener('keydown',(e:KeyboardEvent)=>this.key(e));addEventListener('keyup',(e:KeyboardEvent)=>{if(e.code==='Space'){this.tool=this.prev;this.buildUI()}});document.addEventListener('paste',e=>this.paste(e));document.addEventListener('drop',e=>{e.preventDefault();this.importFiles(e.dataTransfer?.files)});document.addEventListener('dragover',e=>e.preventDefault())}
key(e:KeyboardEvent){if(e.code==='Space'){this.prev=this.tool;this.tool='hand';this.buildUI();return}if(e.ctrlKey&&e.key==='z'){this.restore(this.undo,this.redo);return}if((e.ctrlKey&&e.key==='y')||(e.ctrlKey&&e.shiftKey&&e.key==='Z')){this.restore(this.redo,this.undo);return}const m:any={p:'pen',h:'hand',e:'eraser',r:'rectangle',o:'ellipse',a:'arrow',t:'text',l:'lasso'};if(m[e.key.toLowerCase()]){this.tool=m[e.key.toLowerCase()];this.buildUI()}}
finishStroke(highlighter=false){this.worker.onmessage=ev=>{const pts=ev.data as Point[];const o:Stroke={id:uid(),boardId:this.board.id,layerId:this.layers[0].id,type:'stroke',points:pts,color:highlighter?'#ffd54a':'#f7f7f7',width:highlighter?18:3,highlighter,bounds:boundsOfPoints(pts,20),rotation:0,z:Date.now(),created:Date.now(),updated:Date.now()};this.add(o)};this.worker.postMessage({points:this.stroke,stabilization:this.stab})}
add(o:SceneObject,recordUndo=true){if(recordUndo)this.undo.push([...this.objects]);const cells=chunksForBounds(o.bounds);for(const c of cells){const id=chunkId(this.board.id,c.cx,c.cy),ch=this.chunks.get(id)||{id,boardId:this.board.id,cx:c.cx,cy:c.cy,objects:[],loadedAt:Date.now(),dirty:true};ch.objects.push(o);ch.dirty=true;this.chunks.set(id,ch)}this.qt.insert(o);this.objects.push(o)}erase(path:Point[]){this.undo.push([...this.objects]);const b=boundsOfPoints(path,32),hit=this.qt.query(b);const near=(p:Point)=>path.some(q=>Math.hypot(p.x-q.x,p.y-q.y)<18);for(const o of hit)if(o.type==='stroke'){this.removeObj(o.id);let seg:Point[]=[];for(const p of o.points){if(near(p)){if(seg.length>1)this.add({...o,id:uid(),points:seg,bounds:boundsOfPoints(seg,20),created:Date.now(),updated:Date.now()},false);seg=[]}else seg.push(p)}if(seg.length>1)this.add({...o,id:uid(),points:seg,bounds:boundsOfPoints(seg,20),created:Date.now(),updated:Date.now()},false)}}
removeObj(id:string){this.objects=this.objects.filter(x=>x.id!==id);this.qt.remove(id);for(const ch of this.chunks.values()){ch.objects=ch.objects.filter((x:SceneObject)=>x.id!==id);ch.dirty=true}}
reindex(){for(const ch of this.chunks.values()){ch.objects=[];ch.dirty=true}this.qt.clear();const snapshot=[...this.objects];this.objects=[];for(const o of snapshot){const cells=chunksForBounds(o.bounds);for(const c of cells){const id=chunkId(this.board.id,c.cx,c.cy),ch=this.chunks.get(id)||{id,boardId:this.board.id,cx:c.cx,cy:c.cy,objects:[],loadedAt:Date.now(),dirty:true};ch.objects.push(o);ch.dirty=true;this.chunks.set(id,ch)}this.qt.insert(o);this.objects.push(o)}}
restore(from:SceneObject[][],to:SceneObject[][]){const s=from.pop();if(!s)return;to.push([...this.objects]);this.objects=s;this.reindex();}
async saveDirty(){for(const ch of this.chunks.values())if(ch.dirty){ch.dirty=false;await this.db.put('chunks',ch)}this.board.updated=Date.now();await this.db.put('boards',this.board)}
buildUI(){this.ui.className='ui';this.ui.innerHTML=`<aside><h1>🫘 BeansBoard</h1><button id=new>New board</button><input id=search placeholder=Search><div id=boards></div><h2>Layers</h2><div id=layers></div></aside><nav>${['pen','highlighter','eraser','rectangle','ellipse','arrow','text','lasso','hand'].map(t=>`<button class="${this.tool===t?'on':''}" data-tool=${t}>${t}</button>`).join('')}<button id=grid>Grid</button><label>Stabilize <input id=stab type=range min=0 max=100 value=${this.stab}></label></nav>`;this.ui.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{this.tool=(b as HTMLElement).dataset.tool as Tool;this.buildUI()}));this.ui.querySelector('#grid')!.addEventListener('click',()=>this.r.grid=!this.r.grid);(this.ui.querySelector('#stab') as HTMLInputElement).oninput=e=>this.stab=+(e.target as HTMLInputElement).value;this.db.all<Board>('boards').then(bs=>{const el=this.ui.querySelector('#boards')!;el.innerHTML=bs.sort((a,b)=>b.updated-a.updated).map(b=>`<button data-b=${b.id}>${b.favorite?'★':'☆'} ${b.name}</button>`).join('');el.querySelectorAll('button').forEach(x=>x.addEventListener('click',()=>this.loadBoard((x as HTMLElement).dataset.b!)))});this.ui.querySelector('#new')!.addEventListener('click',async()=>{const now=Date.now(),id=uid();await this.db.put('boards',{id,name:'Untitled Board',created:now,updated:now,favorite:false,folder:'General',subject:'',chapter:'',recent:now});await this.db.put('layers',{id:uid(),boardId:id,name:'Layer 1',visible:true,locked:false,order:0} as any);await this.loadBoard(id);this.buildUI()});const le=this.ui.querySelector('#layers')!;le.innerHTML=this.layers.map(l=>`<label><input type=checkbox ${l.visible?'checked':''} data-l=${l.id}> ${l.name}</label>`).join('');le.querySelectorAll('input').forEach(i=>(i as HTMLInputElement).onchange=()=>{const l=this.layers.find(l=>l.id===(i as HTMLInputElement).dataset.l)!;l.visible=(i as HTMLInputElement).checked;this.db.put('layers',l as any)})}
paste(e:ClipboardEvent){const f=e.clipboardData?.files;this.importFiles(f)}importFiles(files?:FileList|null){if(!files)return;[...files].forEach(f=>{const rd=new FileReader();rd.onload=()=>{const p=this.screen({clientX:innerWidth/2,clientY:innerHeight/2,pressure:.5} as any);this.add({id:uid(),boardId:this.board.id,layerId:this.layers[0].id,type:'text',text:`Imported ${f.name} (${f.type||'file'})`,color:'#9ee7ff',fontSize:24,bounds:{x:p.x,y:p.y,w:360,h:36},rotation:0,z:Date.now(),created:Date.now(),updated:Date.now()} as any)};rd.readAsDataURL(f)})}}
new App().start();
